### ISSUE TITLE
Have a quesstion:Call to a member function getColumns() on null 

### ISSUE THREAD

**Issue by kopalam** [biliboobrian/lumen-angular-code-generator#1]
I try install composer ,and finished setting. 

But when I bilibo:lumen:model TabTools, Error :Call to a member function getColumns() on null 

I make sure I have this table,and lumen can select table info.

So I need for help this quesstion

**Comment by kopalam** [comment]
oh yet , have one thing,My lumen version is 5.7
maybe about a version?

**Comment by kopalam** [comment]
I try it something,The quession is finish. 
Becase my table no primary key. so ,the column is null.
I think This is not the same as mandatory primary keys.

**Comment by biliboobrian** [comment]
Hello thanks for your question :) yes primary key is needed for generation, and primary column default name is 'id'. do not hesitate for any question ;)
