### ISSUE TITLE
Lumen (6.1.0) Can't use thie package

### ISSUE THREAD

**Issue by kopalam** [biliboobrian/lumen-angular-code-generator#2]
Halo,Just now I Test this package,In the Lumen (6.1.0)(Laravel Components ^6.0) Looks like can not use this package.

If you have some time,I hold you can fixed this quession.

Thx .I so like this package in the lumen ,It helped me a lot.

**Comment by biliboobrian** [comment]
I have updated the package and dependencies to provide compatibility with lumen 6.*.

Tell me if you get any problem.

**Comment by kopalam** [comment]
thank you ! You are best !
