### ISSUE TITLE
Fatal error: Class 'biliboobrian\MicroServiceModelUtils\Models\MicroServiceBaseModel' not found

### ISSUE THREAD

**Issue by kopalam** [biliboobrian/lumen-angular-code-generator#3]
Fatal error: Class 'biliboobrian\MicroServiceModelUtils\Models\MicroServiceBaseModel' not found in /www/wwwroot/funx/vendor/biliboobrian/lumen-angular-code-generator/src/Model/MicroServiceExtendModel.php on line 16

It's a bug need fix?
In this path
**biliboobrian/lumen-angular-code-generator/src/Model/MicroServiceExtendModel.php**

looks like use Error,So I try it edit 
**before** 
use biliboobrian\MicroServiceModelUtils\Models\MicroServiceBaseModel;
**after**
use LushDigital\MicroServiceModelUtils\Models\MicroServiceBaseModel;

**It's ok.**

**Comment by kopalam** [comment]
Because MicroServiceBaseModel  this model ,namespace is LushDigital\MicroServiceModelUtils\Models;
maybe need you fix it the little bug.

thank you

**Comment by biliboobrian** [comment]
Hello,

What version are you using?

LushDigital packages do not support last version of lumen so i have forked them on my github to continu using them.

with version 1.0.31 you should not have dependencies problems, please try to clear vendor and composer cache and reinstall them to see if any problem :)

let me know
